name: Deploy NomozVaqtlari Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master  # yoki sizning asosiy branch'ingiz

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'  # Sizning .NET versiyangiz
    
    - name: Restore dependencies
      run: dotnet restore NomozVaqtlari/NomozVaqtlari.csproj
    
    - name: Build NomozVaqtlari Blazor WebAssembly project
      run: dotnet publish NomozVaqtlari/NomozVaqtlari.csproj --configuration Release --output ./build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./build/wwwroot  # To'g'ri papkaga yo'naltirishni tekshiring (index.html shu yerda bo'lishi kerak)
        token: ${{ secrets.GITHUB_TOKEN }}
